AppBundle\Entity\Article:
  type: entity
  table: null
  repositoryClass: AppBundle\Repository\ArticleRepository
  id:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      length: 255
    price:
      type: float
    typeArticle:
      type: string
      length: 255
    stock:
      type: integer
  manyToMany:
    bills:
      targetEntity: AppBundle\Entity\Bill
      mappedBy: articles
  lifecycleCallbacks: {  }
